version: '3.8'
services:
  redis:
    image: redis:7
    container_name: onceheard_redis
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data: